---
- name: Restart Apache2
  service: name=apache2 state=restarted

- name: Restart Nginx
  service: name=nginx state=restarted

- name: Restart HHVM
  service: name=hhvm state=restarted

- name: Restart PHP5 FPM
  service: name=php5-fpm state=restarted
